### PR TITLE
Remove </meta> to prevent IE10 from breaking

### PR DESCRIPTION
**Pull request by janwerkhoven**
This PR fixes a bug that occurs in IE10 as described here:
https://github.com/damiencaselli/ember-cli-sentry/issues/104

### CODE REVIEW

**Comment by dschmidt** [comment]
Does the bug also occur with `return '<meta name="sentry:revision" />';`?

**Comment by janwerkhoven** [comment]
This is the screenshot of a user showing an error on IE10 breaking the page:

screen shot 2017-10-26 at 1 12 30 pm

The error points at line 57 which is this screenshot:

screen shot 2017-10-25 at 2 51 36 pm

So far I haven't been able to reliably reproduce the bug. When I open up IE10 in Browserstack, no such errors occur, even thought the `</meta>` is present.

screen shot 2017-10-26 at 12 26 26 pm

Regardless the reproduction of this error, it's safe to say that the web standard for `<meta>` tags is to not include `</meta>` nor `/>`.

https://www.w3.org/TR/html5/document-metadata.html#the-meta-element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

What do you think?

**Comment by dschmidt** [comment]
Okay, if the standard says "don't include it", we don't include it either :-)

**Comment by dschmidt** [comment]
Will try to cut a release later today

**Comment by janwerkhoven** [comment]
Thanks a bunch!

**Comment by janwerkhoven** [comment]
Has the release gone out?
We still have IE10 users stranded and complaining, unable to user our app.

**Comment by dschmidt** [comment]
@janwerkhoven Now it has (v0.5.3). I'm so sorry, I completely forgot about this :-(

**Comment by janwerkhoven** [comment]
Legend, thanks!

**Pull request merged**
