### PR TITLE
Fix authentication issues

### PR DESCRIPTION
**Pull request by Turbo87**
This PR is fixing some issues when authenticating against sentry.io via bearer token.

### CODE REVIEW

**Comment by Turbo87** [comment]
@dschmidt any comments?

**Comment by jessepollak** [comment]
+1

**Comment by dschmidt** [comment]
I was using request before but @duizendnegen ported my code to use form-data directly (https://github.com/dschmidt/ember-cli-deploy-sentry/pull/6) ... I'm a bit clueless here, what to do :\

**Comment by duizendnegen** [comment]
Uhh what kind of errors were you getting @Turbo87 when authenticating against Sentry?
(is this because of their new auth?)

**Comment by Turbo87** [comment]
@duizendnegen yes, it seems that `formData.submit()` only supports HTTP Basic Auth, but not using Bearer tokens like sentry.io is essentially requiring now. I didn't know that it was using `request` directly before. IMHO we should try to fix request though instead using two different form of making authenticated HTTP requests. did you try to debug your original issue or extract a reproduction?

**Comment by jessepollak** [comment]
Just to chime in: @Turbo87's resolved the issue for us. One semi-related thing is that the `sentryApiKey` is required in the validation step even if `sentryBearerApiKey` is set!

**Comment by duizendnegen** [comment]
Then let's go - I need to make the transition to Bearer anyway, and I'm not deploying with Windows anymore.

**Comment by dschmidt** [comment]
@duizendnegen So ... merge this? 
I thought you were going to take care of this, I think you have write access to this repo :D

**Comment by duizendnegen** [comment]
Feel free to merge, I don't have write access :)

**Comment by dschmidt** [comment]
Thanks a lot

**Comment by dschmidt** [comment]
@duizendnegen invited you as collaborator :)

**Pull request merged**
