### PR TITLE
fill a meta tag with the current revision when uploading

### PR DESCRIPTION
**Pull request by duizendnegen**

### CODE REVIEW

**Comment by dschmidt** [comment]
I would like to have it a bit more configurable, e.g. the meta name, the index.html file name (probably a minimatch on distFiles) and also to be able to opt out of the feature. The meta name isnt too important, I'll happily take care of it, but would you mind adding includePattern and a switchoff option plus documentation?

**Comment by duizendnegen** [comment]
What's the use case for changing meta & index.html? Switchoff sounds good though.

**Comment by dschmidt** [comment]
i have multiple apps and so multiple index.html files - someone might need it ... for whatever :-)

Meta, well, not too important. As i said i will take care of it.

**Comment by duizendnegen** [comment]
Added the disabling option + some docs.
As for reading distFiles, it'll be a bit until I get around to doing that, maybe next weekend only.

**Comment by dschmidt** [comment]
Really cool, one last minor thing: 
I know I said "switchoff option", but I always find `disabled` options rather unfortunate, can you make it enabled with default `true`?

Then I'll merge!

**Comment by duizendnegen** [comment]
yep, done

**Comment by dschmidt** [comment]
Neat, thanks!

**Pull request merged**
